# config/aws.yml
defaults: &defaults
  access_key_id: <%=ENV["AWS_ACCESS_KEY_ID"]%>
  secret_access_key: <%=ENV["AWS_SECRET_ACCESS_KEY"]%>
development:
  <<: *defaults
  bucket: "makely-development"
test:
  <<: *defaults
  bucket: "makely-test"
production:
  access_key_id: <%=ENV["AWS_ACCESS_KEY_ID"]%>
  secret_access_key: <%=ENV["AWS_SECRET_ACCESS_KEY"]%>
  bucket: "makely"